<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Series;
use App\Models\Content;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;

class ProductionDataSeeder extends Seeder
{
    public function run(): void
    {
        // Disable foreign key checks for clean seeding
        Schema::disableForeignKeyConstraints();
        
        // 1. Seed Admin User
        User::updateOrCreate(
            ['email' => 'admin@tlq.com'],
            [
                'name' => 'Admin TLQ',
                'password' => Hash::make('admin123'), // Default password, user should change
                'is_admin' => true,
            ]
        );

        // 2. Seed Series
        $series = [
            ['id' => 1, 'name' => 'Miracle', 'slug' => 'miracle', 'color_hex' => '#3730A3', 'description' => 'Keajaiban-keajaiban Al-Quran untuk mempertebal iman.'],
            ['id' => 2, 'name' => 'Parenting', 'slug' => 'parenting', 'color_hex' => '#EA580C', 'description' => 'Panduan mendidik anak sesuai nilai-nilai Al-Quran.'],
            ['id' => 3, 'name' => 'Huffaz', 'slug' => 'huffaz', 'color_hex' => '#0284C7', 'description' => 'Motivasi dan panduan bagi para penjaga Al-Quran.'],
            ['id' => 4, 'name' => 'Marriage', 'slug' => 'married', 'color_hex' => '#D97706', 'description' => 'Membangun keluarga sakinah, mawaddah, wa rahmah.'],
            ['id' => 5, 'name' => 'Healing', 'slug' => 'healing', 'color_hex' => '#E63995', 'description' => 'Menemukan ketenangan dan pemulihan jiwa melalui Al-Quran.'],
        ];

        foreach ($series as $s) {
            Series::updateOrCreate(['id' => $s['id']], $s);
        }

        // 3. Seed Contents
        $contents = [
            ['id' => 1, 'series_id' => 1, 'surah_ayah' => 'Al-Baqarah: 164', 'arabic_text' => 'إِنَّ فِي خَلْقِ السَّمَاوَاتِ وَالْأَرْضِ...', 'translation' => 'Sesungguhnya dalam penciptaan langit dan bumi...', 'insight' => 'Ayat ini mengajak kita merenungi keteraturan alam semesta sebagai bukti kebesaran Ilahi.', 'action_plan' => 'Luangkan waktu 5 menit hari ini untuk menatap langit/pohon dan mengucap Subhanallah.'],
            ['id' => 2, 'series_id' => 2, 'surah_ayah' => 'Luqman: 13', 'arabic_text' => 'وَإِذْ قَالَ لُقْمَانُ لِابْنِهِ وَهُوَ يَعِظُهُ يَا بُنَيَّ لَا تُشْرِكْ بِاللَّهِ...', 'translation' => 'Dan ingatlah ketika Luqman berkata kepada anaknya...', 'insight' => 'Pilar utama mendidik anak adalah menanamkan Tauhid dengan penuh kasih sayang.', 'action_plan' => 'Berikan pelukan hangat pada sikecil dan bisikkan satu kalimat motivasi Islami.'],
            ['id' => 3, 'series_id' => 3, 'surah_ayah' => 'Al-Qamar: 17', 'arabic_text' => 'وَلَقَدْ يَسَّرْنَا الْقُرْآنَ لِلذِّكْرِ فَهَلْ مِن مُّدَّكِرٍ', 'translation' => 'Dan sesungguhnya telah Kami mudahkan Al-Quran untuk pelajaran...', 'insight' => 'Al-Quran dijamin mudah jika kita memiliki tekad dan keistiqomahan.', 'action_plan' => 'Murojaah 5 ayat terakhir yang dihafal sebelum tidur malam ini.'],
            ['id' => 4, 'series_id' => 4, 'surah_ayah' => 'Ar-Rum: 21', 'arabic_text' => 'وَمِنْ آيَاتِهِ أَنْ خَلَقَ لَكُم مِّنْ أَنفُسِكُمْ أَزْوَاجًا لِّتَسْكُنُوا إِلَيْهَا...', 'translation' => 'Dan di antara tanda-tanda kekuasaan-Nya ialah Dia menciptakan untukmu isteri-isteri...', 'insight' => 'Pasangan adalah ketenangan (Sakinah). Kunci rumah tangga adalah kasih sayang (Mawaddah & Rahmah).', 'action_plan' => 'Ucapkan terima kasih atas hal kecil yang dilakukan pasangan hari ini.'],
            ['id' => 5, 'series_id' => 1, 'surah_ayah' => 'QS. Ali Imran : 173', 'arabic_text' => 'ٱلَّذِينَ قَالَ لَهُمُ ٱلنَّاسُ إِنَّ ٱلنَّاسَ قَدْ جَمَعُوا۟ لَكُمْ فَٱخْشَوْهُمْ فَزَادَهُمْ إِيمَـٰنًا وَقَالُوا۟ حَسْبُنَا ٱللَّهُ وَنِعْمَ ٱلْوَكِيلُ', 'translation' => '"Cukuplah Allah menjadi penolong kami dan Allah adalah sebaik-baik pelindung"', 'insight' => 'Ketika semua terlihat mustahil, Aku tetap cukup untuk menolongmu', 'action_plan' => 'Baca Hasbunallah wa ni\'mal wakil 33x hari ini dengan penuh yakin'],
            ['id' => 6, 'series_id' => 1, 'surah_ayah' => 'QS. Yunus: 58', 'arabic_text' => 'قُلْ بِفَضْلِ ٱللَّهِ وَبِرَحْمَتِهِۦ فَبِذَٰلِكَ فَلْيَفْرَحُوا۟ هُوَ خَيْرٌ مِّمَّا يَجْمَعُونَ', 'translation' => '"Dengan karunua ALLah dan rahmat-Nya, hendaklah dengan itu mereka bergembira."', 'insight' => '"Bagahia tak harus sempurna, Cukup sadar bahwa aku bersamamu."', 'action_plan' => 'Tersenyumlah sepanjang hari ini sebagai tanda syukur, meski hanya untuk dirimu sendiri'],
            ['id' => 7, 'series_id' => 1, 'surah_ayah' => 'Al Baqarah : 214', 'arabic_text' => 'اِنَّ نَصْرَ اللّٰهِ قَرِيْبٌ', 'translation' => 'Sesungguhnya pertolongan Allah itu dekat', 'insight' => 'Bahkan sebelum kamu selesai mengeluh, pertolonganKu sudah menuju kepadamu', 'action_plan' => 'Jadilah kemudahan bagi orang lain, berikan pertolonganmu kepada orang hari ini'],
            ['id' => 8, 'series_id' => 1, 'surah_ayah' => 'QS Al Insyirah 8', 'arabic_text' => 'وَاِلٰى رَبِّكَ فَارْغَبْ ۙ', 'translation' => 'Dan kepada Tuhanmulah hendaknya kamu berharap', 'insight' => 'Letakkan hendaknyasepenuhnya padaKu dan Aku akan buktikan bahwa harapan itu tidak sia sia', 'action_plan' => 'Sebelum tidur, sebutkan satu impianmu yang ingin kau titipkan penuh pada Allah'],
            ['id' => 9, 'series_id' => 1, 'surah_ayah' => 'QS At Talaq : 3', 'arabic_text' => 'وَيَرْزُقْهُ مِنْ حَيْثُ لَا يَحْتَسِبُ', 'translation' => 'Dan Dia memberi rezeki dari arah yang tidak disangka sangka', 'insight' => 'Jangan batasi caraKu, sebab Aku punya jalan diluar logikamu', 'action_plan' => 'Sedekah hari ini meskipun sedikit, lalu katakan dalam hati. "Aku percaya rejekiku ditangani oleh Allah"'],
            ['id' => 10, 'series_id' => 1, 'surah_ayah' => 'QS Ar Rum : 60', 'arabic_text' => 'فَاصْبِرْ اِنَّ وَعْدَ اللّٰهِ حَقٌّ وَّ', 'translation' => 'Maka bersabarlah kamu, sesungguhnya janji Allah adalah benar', 'insight' => 'Yang kau tunggu pasti datang, hanya saja Aku sedang menyiapkan agar pantas menerimanya', 'action_plan' => 'Tahan diri dari membuat keputusan tergesa gesa hari ini'],
            ['id' => 11, 'series_id' => 1, 'surah_ayah' => 'QS Al Baqarah : 271', 'arabic_text' => 'اِنْ تُبْدُوا الصَّدَقٰتِ فَنِعِمَّا هِيَۚ وَاِنْ تُخْفُوْهَا وَتُؤْتُوْهَا الْفُقَرَاۤءَ فَهُوَ خَيْرٌ لَّكُمْۗ وَيُكَفِّرُ عَنْكُمْ مِّنْ سَيِّاٰتِكُمْۗ', 'translation' => '"Jika kamu menampakkan sedekah-sedekahmu, maka itu baik. Dan jika kamu menyembunyikannya dan memberikannya kepada orang-orang fakir, maka itu lebih baik bagimu"', 'insight' => 'Sedekah yang kau lakukan dalam diam, Aku melihatnya dan pasti akan membalasnya', 'action_plan' => 'Lakukan sedekah secara langsung, tapi tanpa diketahuipenerimanya bahwa itu dari kamu'],
            ['id' => 12, 'series_id' => 1, 'surah_ayah' => 'QS Al Baqarah : 286', 'arabic_text' => "لَا يُكَلِّفُ اللّٰهُ نَفْسًا اِلَّ لَا وُسْعَهَا", 'translation' => 'Allah tidak membebani seseorang melainkan sesuai dengan kesanggupannya.', 'insight' => 'Jika Aku beri beban, itu karena Aku tahu kamu bisa', 'action_plan' => 'Ucapkan "aku kuat karena Allah menguatkanku", dan hadapi tantangan hari ini'],
            ['id' => 13, 'series_id' => 1, 'surah_ayah' => 'QS Al Baqarah : 186', 'arabic_text' => 'وَاِذَا سَاَلَ عِبَادِيْ عَنِّيْ فَاِنِّيْ قَرِيْبٌۗ اُجِيْبُ دَعْوَةَ الدَّاعِ اِذَا دَعَانِۙ', 'translation' => 'Apabila hamba-hamba-Ku bertanya kepadamu (Nabi Muhammad) tentang Aku, sesungguhnya Aku dekat. Aku mengabulkan permohonan orang yang berdoa apabila dia berdoa kepada-Ku', 'insight' => 'Aku takpernah menjauh darimu, setiap kalikau memanggiKu, Aku mendengar. Jangan ragu ragu berbicaralah pada Ku', 'action_plan' => 'Ambil waktu 1 menit untuk menyebut nama Allah dan utarakan isi hatimu'],
            ['id' => 14, 'series_id' => 1, 'surah_ayah' => 'QS Asy Syura : 19', 'arabic_text' => 'اَللّٰهُ لَطِيْفٌۢ بِعِبَادِهٖ يَرْزُقُ مَنْ يَّشَاۤءُۚ', 'translation' => 'Allah Maha lembut terhadap hamba-hamba-Nya. Dia memberi rezeki kepada siapa yang Dia kehendaki', 'insight' => 'Rezeki yang kau tunggu tidak datang karena keras usaha, tapi karena lembutnya cintaKu', 'action_plan' => 'Berdo\'alah dengan lembut, Yakinkan hatimu bahwa Allah tidak lupa padamu'],
            ['id' => 15, 'series_id' => 1, 'surah_ayah' => 'QS Al Hadid : 23', 'arabic_text' => 'لِّكَيْلَا تَأْسَوْا عَلَىٰ مَا فَاتَكُمْ وَلَا تَفْرَحُوا بِمَآ ءَاتَىٰكُمْ ۗ', 'translation' => '(Kami jelaskan yang demikian itu) supaya kamu jangan berduka cita terhadap apa yang luput dari kamu, dan supaya kamu jangan terlalu gembira terhadap apa yang diberikan-Nya kepadamu.', 'insight' => 'Apa pun yang Aku ambil,Aku gantikan.Apapun yang Aku beri adalah ujian.Tetaplah dekat', 'action_plan' => 'Hari ini,latih hati dengan berkata, " Inilah yang terbaik menurut Allah"'],
            ['id' => 16, 'series_id' => 1, 'surah_ayah' => 'QS At Taubah : 51', 'arabic_text' => 'قُلْ لَّنْ يُّصِيْبَنَآ اِلَّا مَا كَتَبَ اللّٰهُ لَنَاۚ هُوَ مَوْلٰىنَا', 'translation' => '"Katakanlah (Muhammad), “Tidak akan menimpa kami melainkan apa yang telah ditetapkan Allah bagi kami"', 'insight' => 'Apa pun yang terjadi padamu hari ini. Aku yang izinkan. Dan Aku tahu itu demi kebaikanmu', 'action_plan' => 'Ucapkan "Qodarullah wa ma syaa\'afa\'ala" saat hal tak sesuai harapanmu'],
            ['id' => 17, 'series_id' => 1, 'surah_ayah' => 'QS Al Baqarah : 280', 'arabic_text' => 'وَاَنْ تَصَدَّقُوْا خَيْرٌ لَّكُمْ اِنْ كُنْتُمْ تَعْلَمُوْنَ', 'translation' => 'Kamu bersedekah (membebaskan utang) itu lebih baik bagimu apabila kamu mengetahui(-nya).', 'insight' => 'Aku akan memudahkan rezekimu, ketika kamu memudahkan kesusahan orang lain', 'action_plan' => 'Bebaskanlah hutang orang padamu, Sebagian atau seluruhnya'],
            ['id' => 18, 'series_id' => 1, 'surah_ayah' => 'QS Al Baqarah : 286', 'arabic_text' => 'لَا يُكَلِّفُ اللّٰهُ نَفْسًا اِلَّا وُسْعَهَا', 'translation' => 'Allah tidak membebani hamba-Nya melainkan sesuai kesanggupannya', 'insight' => 'Kuat itu bukan karena kamu mampu, tapi karena Aku bantu.Kau tak sendiri menanggungnya', 'action_plan' => 'Tulis satu tantangan yang sedang kamu hadapi, lalu serahkan dalam do\'a pada Allah'],
            ['id' => 19, 'series_id' => 1, 'surah_ayah' => 'QS Al A\'raf 56', 'arabic_text' => 'اِنَّ رَحْمَتَ اللّٰهِ قَرِيْبٌ مِّنَ الْمُحْسِنِيْن7', 'translation' => 'Sesungguhnya rahmat Allah sangat dekat dengan orang-orang yang berbuat baik', 'insight' => 'Jadilah pelaku kebaikan hari ini, dan lihat bagaimana Aku mendekat dengan cinta', 'action_plan' => 'Lakukan 1 kebaikan kecil diam-diam untuk seseorang hari ini'],
            ['id' => 20, 'series_id' => 2, 'surah_ayah' => 'QS. Al-Baqarah: 286', 'arabic_text' => 'A', 'translation' => '"Allah tidak membebani seseorang melainkan sesuai kesanggupannya"', 'insight' => 'Aku tahu mendidik itu berat. Tapi tak kubiarkan kau sendiri dalam lelahmu. Ada pahala besar menantimu', 'action_plan' => 'Ambil jeda 5 menit hari ini hanya untuk menguatkan diri, bukan menyerah'],
            ['id' => 21, 'series_id' => 1, 'surah_ayah' => 'QS Ibrahim : 7', 'arabic_text' => 'وَاِذْ تَاَذَّنَ رَبُّكُمْ لَىِٕنْ شَكَرْتُمْ لَاَزِيْدَنَّكُمْ ۖ', 'translation' => '"Dan (ingatlah) ketika Tuhanmu memaklumkan, “Sesungguhnya jika kamu bersyukur, niscaya Aku akan menambah (nikmat) kepadamu"', 'insight' => 'Syukurmu hari ini akan membuka langit keajaiban yang lebih besar dari yang kau minta', 'action_plan' => 'Ucapkan 3 hal yang kamu syukuri dengan lisan dan hati'],
            ['id' => 22, 'series_id' => 2, 'surah_ayah' => 'QS. Al-Anfal: 2', 'arabic_text' => 'A', 'translation' => '"sesungguhnya orang-orang yang beriman ialah mereka yang apabila disebut nama Allah, gemetarlah hati mereka, dan apabila dibacakan ayat-ayat-Nya, bertambahlah iman mereka..."', 'insight' => 'Orang tua yang hatinya hidup akan lebih mudah menumbuhkan iman dalam hati anaknya.', 'action_plan' => 'Sediakan 5 menit setiap hari untuk membaca 1 ayat Al-Qur\'an, lalu bisikan ke hati "Ya Allah, hidupkan imanku... agar anakku melihat cahayaMu melalui aku."'],
            ['id' => 23, 'series_id' => 1, 'surah_ayah' => 'QS Al A\'raf : 56', 'arabic_text' => 'إِنَّ رَحْمَتَ اللَّهِ قَرِيبٌ مِّنَ الْمُحْسِنِينَ', 'translation' => 'Sesungguhnya rahmat Allah amat dekat kepada orang-orang yang berbuat baik', 'insight' => 'Bila kau berbuat baik walau lelah, Aku akan mendekat, memelukmu dengan rahmatKu', 'action_plan' => 'Pilih satu kebaikan spontan hari ini, walau kecil'],
            ['id' => 24, 'series_id' => 2, 'surah_ayah' => 'QS Al-Ahqaf: 15', 'arabic_text' => 'A', 'translation' => '"...dan berbuat baiklah kepada kedua orang tuamu."', 'insight' => 'Jika ingin anakmu berbakti padamu, ajarkan ia cara mencintai Allah lebih dahulu. Dari cinta itu lahir hormat yang murni.', 'action_plan' => 'Ucapkan ke anakmu: "Aku ingin kamu jadi anak yang dicintai Allah."'],
            ['id' => 25, 'series_id' => 1, 'surah_ayah' => 'QS Al Isra : 80', 'arabic_text' => 'وَقُلْ رَّبِّ اَدْخِلْنِيْ مُدْخَلَ صِدْقٍ وَّاَخْرِجْنِيْ مُخْرَجَ صِدْقٍ', 'translation' => 'Katakanlah (Nabi Muhammad), “Ya Tuhanku, masukkan aku (ke tempat dan keadaan apa saja) dengan cara yang benar"', 'insight' => 'Aku kan tuntun langkahmu ke tempat yang penuh berkah, asal kau mau menggenggam tanganKu', 'action_plan' => 'Minta petunjuk Allah dalam satu hal penting hari ini sebelum melangkah, gunakan do\'a istikharah'],
            ['id' => 26, 'series_id' => 2, 'surah_ayah' => 'QS. At-Tahrim: 12', 'arabic_text' => 'A', 'translation' => '"Dan Maryam binti Imran yang memelihara kehormatannya..."', 'insight' => 'Allah muliakan anak yang menjaga diri dan nilai..', 'action_plan' => 'Pasang batas gadget, awasi tontonan, dan jadikan obrolan tentang adab aurat sebagai percakapan rutin, bukan teguran marah.'],
            ['id' => 27, 'series_id' => 1, 'surah_ayah' => 'QS Asy Syura : 19', 'arabic_text' => 'اَللّٰهُ لَطِيْفٌۢ بِعِبَادِهٖ', 'translation' => 'Allah Maha Lembut terhadap hambaNya', 'insight' => 'Aku takakan menyakitimu.Semua yang Aku ijinkan terjadi sedang membentukmu menuju kuat dan indah', 'action_plan' => 'Ucapkan "Yaa Rabb ,aku terima semua ketetapanMu. Jadikan aku hambaMu yang kau cintai. Alhamdulillah"'],
            ['id' => 28, 'series_id' => 2, 'surah_ayah' => 'QS. Al-Baqarah: 155', 'arabic_text' => 'A', 'translation' => '"Dan sampaikan kabar gembira kepada orang-orang yang sabar."', 'insight' => 'Sabar menghadapi anak adalah bentuk ibadah yang Allah beri kabar gembira.', 'action_plan' => 'Saat anak tantrum atau membantah, tarik nafas dalam, diam 5 detik, lalu respon dengan hati dingin.'],
            ['id' => 29, 'series_id' => 1, 'surah_ayah' => 'QS Al Anfal : 74', 'arabic_text' => 'وَالَّذِيْنَ اٰمَنُوْا وَهَاجَرُوْا وَجَاهَدُوْا فِيْ سَبِيْلِ اللّٰهِ وَالَّذِيْنَ اٰوَوْا وَّنَصَرُوْآ', 'translation' => 'Orang-orang yang beriman, berhijrah, dan berjihad di jalan Allah, serta orang-orang yang memberi tempat kediaman dan memberi pertolongan', 'insight' => 'Percayalah kedpaKu, aku selalu menjaga orang yang meningglkan kemudharatan karenaKu', 'action_plan' => 'Berjanjilah 1 hal maksiat/ kesalahan yang akan kau tinggalkan, istighfarkan dan tinggalkanlah'],
            ['id' => 30, 'series_id' => 1, 'surah_ayah' => 'QS Yusuf 19', 'arabic_text' => 'وَاللّٰهُ عَلِيْمٌ ۢ بِمَا يَعْمَلُوْنَ', 'translation' => 'Dan Allah Maha Mengetahui apa yang mereka kerjakan', 'insight' => 'Tak ada yang luput dari penglihatan Ku. Setiap air matamu, setiap sabarmu, semua Aku catat', 'action_plan' => 'Bersyukurlah dan lakukanlah satu hal kecil yang selama ini belum kamukerjakan dalam diam'],
            ['id' => 31, 'series_id' => 1, 'surah_ayah' => 'QS At Talaq : 3', 'arabic_text' => 'وَمَنْ يَّتَوَكَّلْ عَلَى اللّٰهِ فَهُوَ حَسْبُهٗ ۗ اِنَّ اللّٰهَ بَالِغُ اَمْرِهٖ', 'translation' => 'Dan barangsiapa bertawakal kepada Allah, niscaya Allah akan mencukupkan (keperluan)nya.', 'insight' => 'Aku tidak membiarkanmu berjuang sendiri. Tawakalmu adalah pintu datangnya pertolonganKu', 'action_plan' => 'Hari ini pasrahkan semua urusanmu seteah berusaha meksimal.Jangan panik'],
            ['id' => 32, 'series_id' => 1, 'surah_ayah' => 'QS Al Mumtahanah : 4', 'arabic_text' => 'رَبَّنَا عَلَيْكَ تَوَكَّلْنَا وَاِلَيْكَ اَنَبْنَا', 'translation' => 'Kami bertawakal kepada Allah. KepadaNya kami berserah', 'insight' => 'Kamu bisa tenang jika tahu Aku yang mengurus hasilnya', 'action_plan' => 'Bayangkan keinginanmu hari ini sudah Allah berikan, sambil lisan mengucap "Yaa Hasiib ... Yaa Rozaaq"'],
            ['id' => 33, 'series_id' => 1, 'surah_ayah' => 'QS Ghafir : 60', 'arabic_text' => 'اَسْتَجِبْ لَكُمْۗ اِنَّ الَّذِيْنَ يَسْتَكْبِرُوْنَ', 'translation' => 'Berdo\'alah kepadaKu, niscaya akan Kuperkenankan bagimu', 'insight' => 'Jangan tunda do\'a hari ini,sebab Aku lebih dekat dari detak hatimu', 'action_plan' => 'Sisihkan waktu 5 menit untuk do\'a penuh keyakinan dan harap'],
            ['id' => 34, 'series_id' => 1, 'surah_ayah' => 'QS Al Anfal : 9', 'arabic_text' => 'اِذْ تَسْتَغِيْثُوْنَ رَبَّكُمْ فَاسْتَجَابَ لَكُمْ', 'translation' => '(Ingatlah) ketika kamu memohon pertolongan kepada Tuhanmu, lalu Dia mengabulkan(-nya)', 'insight' => 'Tangismu tak pernah sia-sia. Aku mendengar setiap desahmu. PertolonganKu lebih dekat dari yang kaubayangkan', 'action_plan' => 'Ucapkan satu do\'a sambil sujud hari ini'],
            ['id' => 35, 'series_id' => 1, 'surah_ayah' => 'QS At Talaq: 2-3', 'arabic_text' => 'وَمَنۡ يَّتَّقِ اللّٰهَ يَجۡعَلۡ لَّهٗ مَخۡرَجًا ۙ', 'translation' => 'Barangsiapa bertakwa kepada Allah niscaya Dia akan membukakan jalan keluar baginya', 'insight' => 'Ketaatanmu takkan sia-sia.Bersabarlah, Aku sedang menyiapkan keajaiban dariarah yang tak kau sangka', 'action_plan' => 'Hindari satu maksiat hari ini dan tambah amalanmu sebagai bentuk takwamu'],
            ['id' => 36, 'series_id' => 1, 'surah_ayah' => 'QS Ghafir : 60', 'arabic_text' => 'رَبُّكُمُ ادْعُوْنِيْٓ اَسْتَجِبْ لَكُمْۗ', 'translation' => '“Berdoalah kepada-Ku, niscaya akan Aku perkenankan bagimu"', 'insight' => 'Tak perlu kata indah, Aku tahu isi hatimu.Cukup datang padaKu dan Aku akan bukakan jalan', 'action_plan' => 'Tulis satu do\'a yang paling kamu harapkan dan bacakan sebelum tidur'],
            ['id' => 37, 'series_id' => 1, 'surah_ayah' => 'QS An Nahl : 97', 'arabic_text' => 'مَنْ عَمِلَ صَالِحًا مِّنْ ذَكَرٍ اَوْ اُنْثٰى وَهُوَ مُؤْمِنٌ فَلَنُحْيِيَنَّهٗ حَيٰوةً طَيِّبَةًۚ', 'translation' => '"Barangsiapa mengerjakan kebajikan, baik laki-laki maupun perempuan dalam keadaan beriman, maka pasti akan Kami berikan kepadanya kehidupan yang baik"', 'insight' => 'Kebaikanmu takkan hilang. Aku balaas dengan hidup yang damai', 'action_plan' => 'Ambil satu niat kecil hari ini, berbuat baik dengan senyum atau sedekah'],
            ['id' => 38, 'series_id' => 1, 'surah_ayah' => 'QS. Al-hajj:78', 'arabic_text' => 'جِهَادِهِۦۚ هُوَ ٱجْتَبَىٰكُمْ وَمَا جَعَلَ عَلَيْكُمْ فِى ٱلدِّينِ مِنْ حَرَجٍۚ', 'translation' => '"Dia telah memilih kamu, dan Dia tidak menjadikan kesukaran untukmu dalam agama."', 'insight' => '"Aku tidak menciptakan jalan-Ku untuk menyulitkanmu-tapi untuk membebaskanmu"', 'action_plan' => 'Dekatkan dirimu pada ibadah yang ringan, tapi konsisten hari ini'],
        ];

        foreach ($contents as $c) {
            Content::updateOrCreate(['id' => $c['id']], $c);
        }

        Schema::enableForeignKeyConstraints();
    }
}
