-- Database Guide: Import Data Awal TLQ Jar
-- File ini berisi data Admin, Series, dan 38 Content Al-Quran

SET FOREIGN_KEY_CHECKS = 0;

-- 1. DATA USER ADMIN
-- Password: admin123 (Sudah di-hash Laravel)
TRUNCATE TABLE users;
INSERT INTO users (id, name, email, password, is_admin, created_at, updated_at) VALUES
(1, 'Admin TLQ', 'admin@tlq.com', '$2y$12$RCOwXbXy0U.dEq9rNCS3Lu4J8P9K.B9oA1Q5nE.uN0e2O6S7n.KjS', 1, NOW(), NOW());

-- 2. DATA SERIES
TRUNCATE TABLE series;
INSERT INTO series (id, name, slug, color_hex, description, created_at, updated_at) VALUES
(1, 'Miracle', 'miracle', '#3730A3', 'Keajaiban-keajaiban Al-Quran untuk mempertebal iman.', NOW(), NOW()),
(2, 'Parenting', 'parenting', '#EA580C', 'Panduan mendidik anak sesuai nilai-nilai Al-Quran.', NOW(), NOW()),
(3, 'Huffaz', 'huffaz', '#0284C7', 'Motivasi dan panduan bagi para penjaga Al-Quran.', NOW(), NOW()),
(4, 'Marriage', 'marriage', '#D97706', 'Membangun keluarga sakinah, mawaddah, wa rahmah.', NOW(), NOW()),
(5, 'Healing', 'healing', '#E63995', 'Menemukan ketenangan dan pemulihan jiwa melalui Al-Quran.', NOW(), NOW());

-- 3. DATA CONTENTS (38 Ayat & Action Plan)
TRUNCATE TABLE contents;
INSERT INTO contents (id, series_id, surah_ayah, arabic_text, translation, insight, action_plan, created_at, updated_at) VALUES
(1, 1, 'Al-Baqarah: 164', 'إِنَّ فِي خَلْقِ السَّمَاوَاتِ وَالْأَرْضِ...', 'Sesungguhnya dalam penciptaan langit dan bumi...', 'Ayat ini mengajak kita merenungi keteraturan alam semesta sebagai bukti kebesaran Ilahi.', 'Luangkan waktu 5 menit hari ini untuk menatap langit/pohon dan mengucap Subhanallah.', NOW(), NOW()),
(2, 2, 'Luqman: 13', 'وَإِذْ قَالَ لُقْمَانُ لِابْنِهِ وَهُوَ يَعِظُهُ يَا بُنَيَّ لَا تُشْرِكْ بِاللَّهِ...', 'Dan ingatlah ketika Luqman berkata kepada anaknya...', 'Pilar utama mendidik anak adalah menanamkan Tauhid dengan penuh kasih sayang.', 'Berikan pelukan hangat pada sikecil dan bisikkan satu kalimat motivasi Islami.', NOW(), NOW()),
(3, 3, 'Al-Qamar: 17', 'وَلَقَدْ يَسَّرْنَا الْقُرْآنَ لِلذِّكْرِ فَهَلْ مِن مُّدَّكِرٍ', 'Dan sesungguhnya telah Kami mudahkan Al-Quran untuk pelajaran...', 'Al-Quran dijamin mudah jika kita memiliki tekad dan keistiqomahan.', 'Murojaah 5 ayat terakhir yang dihafal sebelum tidur malam ini.', NOW(), NOW()),
(4, 4, 'Ar-Rum: 21', 'وَمِنْ آيَاتِهِ أَنْ خَلَقَ لَكُم مِّنْ أَنفُسِكُمْ أَزْوَاجًا لِّتَسْكُنُوا إِلَيْهَا...', 'Dan di antara tanda-tanda kekuasaan-Nya ialah Dia menciptakan untukmu isteri-isteri...', 'Pasangan adalah ketenangan (Sakinah). Kunci rumah tangga adalah kasih sayang (Mawaddah & Rahmah).', 'Ucapkan terima kasih atas hal kecil yang dilakukan pasangan hari ini.', NOW(), NOW()),
(5, 5, 'QS. Ali Imran : 173', 'ٱلَّذِينَ قَالَ لَهُمُ ٱلنَّاسُ إِنَّ ٱلنَّاسَ قَدْ جَمَعُوا۟ لَكُمْ فَٱخْشَوْهُمْ فَزَادَهُمْ إِيمَـٰنًا وَقَالُوا۟ حَسْبُنَا ٱللَّهُ وَنِعْمَ ٱلْوَكِيلُ', '\"Cukuplah Allah menjadi penolong kami dan Allah adalah sebaik-baik pelindung\"', 'Ketika semua terlihat mustahil, Aku tetap cukup untuk menolongmu', 'Baca Hasbunallah wa ni\'mal wakil 33x hari ini dengan penuh yakin', NOW(), NOW()),
(6, 1, 'QS. Yunus: 58', 'قُلْ بِفَضْلِ ٱللَّهِ وَبِرَحْمَتِهِۦ فَبِذَٰلِكَ فَلْيَفْرَحُوا۟ هُوَ خَيْرٌ مِّمَّا يَجْمَعُونَ', '\"Dengan karunua ALLah dan rahmat-Nya, hendaklah dengan itu mereka bergembira.\"', '\"Bagahia tak harus sempurna, Cukup sadar bahwa aku bersamamu.\"', 'Tersenyumlah sepanjang hari ini sebagai tanda syukur, meski hanya untuk dirimu sendiri', NOW(), NOW()),
(7, 1, 'Al Baqarah : 214', 'اِنَّ نَصْرَ اللّٰهِ قَرِيْبٌ', 'Sesungguhnya pertolongan Allah itu dekat', 'Bahkan sebelum kamu selesai mengeluh, pertolonganKu sudah menuju kepadamu', 'Jadilah kemudahan bagi orang lain, berikan pertolonganmu kepada orang hari ini', NOW(), NOW()),
(8, 1, 'QS Al Insyirah 8', 'وَاِلٰى رَبِّكَ فَارْغَبْ ۙ', 'Dan kepada Tuhanmulah hendaknya kamu berharap', 'Letakkan hendaknyasepenuhnya padaKu dan Aku akan buktikan bahwa harapan itu tidak sia sia', 'Sebelum tidur, sebutkan satu impianmu yang ingin kau titipkan penuh pada Allah', NOW(), NOW()),
(9, 1, 'QS At Talaq : 3', 'وَيَرْزُقْهُ مِنْ حَيْثُ لَا يَحْتَسِبُ', 'Dan Dia memberi rezeki dari arah yang tidak disangka sangka', 'Jangan batasi caraKu, sebab Aku punya jalan diluar logikamu', 'Sedekah hari ini meskipun sedikit, lalu katakan dalam hati. \"Aku percaya rejekiku ditangani oleh Allah\"', NOW(), NOW()),
(10, 1, 'QS Ar Rum : 60', 'فَاصْبِرْ اِنَّ وَعْدَ اللّٰهِ حَقٌّ وَّ', 'Maka bersabarlah kamu, sesungguhnya janji Allah adalah benar', 'Yang kau tunggu pasti datang, hanya saja Aku sedang menyiapkan agar pantas menerimanya', 'Tahan diri dari membuat keputusan tergesa gesa hari ini', NOW(), NOW()),
(11, 1, 'QS Al Baqarah : 271', 'اِنْ تُبْدُوا الصَّدَقٰتِ فَنِعِمَّا هِيَۚ وَاِنْ تُخْفُوْهَا وَتُؤْتُوْهَا الْفُقَرَاۤءَ فَهو خَيْرٌ لَّكُمْۗ وَيُكَفِّرُ عَنْكُمْ مِّنْ سَيِّاٰتِكُمْۗ', '\"Jika kamu menampakkan sedekah-sedekahmu, maka itu baik. Dan jika kamu menyembunyikannya dan memberikannya kepada orang-orang fakir, maka itu lebih baik bagimu\"', 'Sedekah yang kau lakukan dalam diam, Aku melihatnya dan pasti akan membalasnya', 'Lakukan sedekah secara langsung, tapi tanpa diketahuipenerimanya bahwa itu dari kamu', NOW(), NOW()),
(12, 1, 'QS Al Baqarah : 286', 'لَا يُكَلِّفُ اللّٰهُ نَفْسًا اِلَّ لَا وُسْعَهَا', 'Allah tidak membebani seseorang melainkan sesuai dengan kesanggupannya.', 'Jika Aku beri beban, itu karena Aku tahu kamu bisa', 'Ucapkan \"aku kuat karena Allah menguatkanku\", dan hadapi tantangan hari ini', NOW(), NOW()),
(13, 1, 'QS Al Baqarah : 186', 'وَاِذَا سَاَلَ عِبَادِيْ عَنِّيْ فَاِنِّيْ قَرِيْبٌۗ اُجِيْبُ دَعْوَةَ الدَّاعِ اِذَا دَعَانِۙ', 'Apabila hamba-hamba-Ku bertanya kepadamu (Nabi Muhammad) tentang Aku, sesungguhnya Aku dekat. Aku mengabulkan permohonan orang yang berdoa apabila dia berdoa kepada-Ku', 'Aku takpernah menjauh darimu, setiap kalikau memanggiKu, Aku mendengar. Jangan ragu ragu berbicaralah pada Ku', 'Ambil waktu 1 menit untuk menyebut nama Allah dan utarakan isi hatimu', NOW(), NOW()),
(14, 1, 'QS Asy Syura : 19', 'اَللّٰهُ لَطِيْفٌۢ بِعِبَادِهٖ يَرْزُقُ مَنْ يَّشَاۤءُۚ', 'Allah Maha lembut terhadap hamba-hamba-Nya. Dia memberi rezeki kepada siapa yang Dia kehendaki', 'Rezeki yang kau tunggu tidak datang karena keras usaha, tapi karena lembutnya cintaKu', 'Berdo\'alah dengan lembut, Yakinkan hatimu bahwa Allah tidak lupa padamu', NOW(), NOW()),
(15, 1, 'QS Al Hadid : 23', 'لِّكَيْلَا تَأْسَوْا عَلَىٰ مَا فَاتَكُمْ وَلَا تَفْرَحُوا بِمَآ ءَاتَىٰكُمْ path', '(Kami jelaskan yang demikian itu) supaya kamu jangan berduka cita terhadap apa yang luput dari kamu, dan supaya kamu jangan terlalu gembira terhadap apa yang diberikan-Nya kepadamu.', 'Apa pun yang Aku ambil,Aku gantikan.Apapun yang Aku beri adalah ujian.Tetaplah dekat', 'Hari ini,latih hati dengan berkata, \" Inilah yang terbaik menurut Allah\"', NOW(), NOW()),
(16, 1, 'QS At Taubah : 51', 'قُلْ لَّنْ يُّصِيْبَنَآ اِلَّا مَا كَتَبَ اللّٰهُ لَنَاۚ هُوَ مَوْلٰىنَا', '\"Katakanlah (Muhammad), “Tidak akan menimpa kami melainkan apa yang telah ditetapkan Allah bagi kami\"', 'Apa pun yang terjadi padamu hari ini. Aku yang izinkan. Dan Aku tahu itu demi kebaikanmu', 'Ucapkan \"Qodarullah wa ma syaa\'afa\'ala\" saat hal tak sesuai harapanmu', NOW(), NOW()),
(17, 1, 'QS Al Baqarah : 280', 'وَاَنْ تَصَدَّقُوْا خَيْرٌ لَّكُمْ اِنْ كُنْتُمْ تَعْلَمُوْنَ', 'Kamu bersedekah (membebaskan utang) itu lebih baik bagimu apabila kamu mengetahui(-nya).', 'Aku akan memudahkan rezekimu, ketika kamu memudahkan kesusahan orang lain', 'Bebaskanlah hutang orang padamu, Sebagian atau seluruhnya', NOW(), NOW()),
(18, 1, 'QS Al Baqarah : 286', 'لَا يُكَلِّفُ اللّٰهُ نَفْسًا اِلَّا وُسْعَهَا', 'Allah tidak membebani hamba-Nya melainkan sesuai kesanggupannya', 'Kuat itu bukan karena kamu mampu, tapi karena Aku bantu.Kau tak sendiri menanggungnya', 'Tulis satu tantangan yang sedang kamu hadapi, lalu serahkan dalam do\'a pada Allah', NOW(), NOW()),
(19, 1, 'QS Al A\'raf 56', 'اِنَّ رَحْمَتَ اللّٰهِ قَرِيْبٌ مِّنَ الْمُحْسِنِيْن7', 'Sesungguhnya rahmat Allah sangat dekat dengan orang-orang yang berbuat baik', 'Jadilah pelaku kebaikan hari ini, dan lihat bagaimana Aku mendekat dengan cinta', 'Lakukan 1 kebaikan kecil diam-diam untuk seseorang hari ini', NOW(), NOW()),
(20, 2, 'QS. Al-Baqarah: 286', 'A', '\"Allah tidak membebani seseorang melainkan sesuai kesanggupannya\"', 'Aku tahu mendidik itu berat. Tapi tak kubiarkan kau sendiri dalam lelahmu. Ada pahala besar menantimu', 'Ambil jeda 5 menit hari ini hanya untuk menguatkan diri, bukan menyerah', NOW(), NOW()),
(21, 1, 'QS Ibrahim : 7', 'وَاِذْ تَاَذَّنَ رَبُّكُمْ لَىِٕنْ شَكَرْتُمْ لَاَزِيْدَنَّكُمْ ۖ', '\"Dan (ingatlah) ketika Tuhanmu memaklumkan, “Sesungguhnya jika kamu bersyukur, niscaya Aku akan menambah (nikmat) kepadamu\"', 'Syukurmu hari ini akan membuka langit keajaiban yang lebih besar dari yang kau minta', 'Ucapkan 3 hal yang kamu syukuri dengan lisan dan hati', NOW(), NOW()),
(22, 2, 'QS. Al-Anfal: 2', 'A', '\"sesungguhnya orang-orang yang beriman ialah mereka yang apabila disebut nama Allah, gemetarlah hati mereka, dan apabila dibacakan ayat-ayat-Nya, bertambahlah iman mereka...\"', 'Orang tua yang hatinya hidup akan lebih mudah menumbuhkan iman dalam hati anaknya.', 'Sediakan 5 menit setiap hari untuk membaca 1 ayat Al-Qur\'an, lalu bisikan ke hati \"Ya Allah, hidupkan imanku... agar anakku melihat cahayaMu melalui aku.\"', NOW(), NOW()),
(23, 1, 'QS Al A\'raf : 56', 'إِنَّ رَحْمَتَ اللَّهِ قَرِيبٌ مِّنَ الْمُحْسِنِينَ', 'Sesungguhnya rahmat Allah amat dekat kepada orang-orang yang berbuat baik', 'Bila kau berbuat baik walau lelah, Aku akan mendekat, memelukmu dengan rahmatKu', 'Pilih satu kebaikan spontan hari ini, walau kecil', NOW(), NOW()),
(24, 2, 'QS Al-Ahqaf: 15', 'A', '\"...dan berbuat baiklah kepada kedua orang tuamu.\"', 'Jika ingin anakmu berbakti padamu, ajarkan ia cara mencintai Allah lebih dahulu. Dari cinta itu lahir hormat yang murni.', 'Ucapkan ke anakmu: \"Aku ingin kamu jadi anak yang dicintai Allah.\"', NOW(), NOW()),
(25, 1, 'QS Al Isra : 80', 'وَقُلْ رَّبِّ اَدْخِلْنِيْ مُدْخَلَ صِدْقٍ وَّاَخْرِجْنِيْ مخْرَجَ صِدْقٍ', 'Katakanlah (Nabi Muhammad), “Ya Tuhanku, masukkan aku (ke tempat dan keadaan apa saja) dengan cara yang benar\"', 'Aku kan tuntun langkahmu ke tempat yang penuh berkah, asal kau mau menggenggam tanganKu', 'Minta petunjuk Allah dalam satu hal penting hari ini sebelum melangkah, gunakan do\'a istikharah', NOW(), NOW()),
(26, 2, 'QS. At-Tahrim: 12', 'A', '\"Dan Maryam binti Imran yang memelihara kehormatannya...\"', 'Allah muliakan anak yang menjaga diri dan nilai..', 'Pasangan batas gadget, awasi tontonan, dan jadikan obrolan tentang adab aurat sebagai percakapan rutin, bukan teguran marah.', NOW(), NOW()),
(27, 1, 'QS Asy Syura : 19', 'اَللّٰهُ لَطِيْفٌۢ بِعِبَادِهٖ', 'Allah Maha Lembut terhadap hambaNya', 'Aku takakan menyakitimu.Semua yang Aku ijinkan terjadi sedang membentukmu menuju kuat dan indah', 'Ucapkan \"Yaa Rabb ,aku terima semua ketetapanMu. Jadikan aku hambaMu yang kau cintai. Alhamdulillah\"', NOW(), NOW()),
(28, 2, 'QS. Al-Baqarah: 155', 'A', '\"Dan sampaikan kabar gembira kepada orang-orang yang sabar.\"', 'Sabar menghadapi anak adalah bentuk ibadah yang Allah beri kabar gembira.', 'Saat anak tantrum atau membantah, tarik nafas dalam, diam 5 detik, lalu respon dengan hati dingin.', NOW(), NOW()),
(29, 1, 'QS Al Anfal : 74', 'وَالَّذِيْنَ اٰمَنُوْا وَهَاجَرُوْا وَجَاهَدُوْا فِيْ سَبِيْلِ اللّٰهِ وَالَّذِيْنَ اٰوَوْا وَّنَصَرُوْآ', 'Orang-orang yang beriman, berhijrah, dan berjihad di jalan Allah, serta orang-orang yang memberi tempat kediaman dan memberi pertolongan', 'Percayalah kedpaKu, aku selalu menjaga orang yang meningglkan kemudharatan karenaKu', 'Berjanjilah 1 hal maksiat/ kesalahan yang akan kau tinggalkan, istighfarkan dan tinggalkanlah', NOW(), NOW()),
(30, 1, 'QS Yusuf 19', 'وَاللّٰهُ عَلِيْمٌ ۢ بِمَا يَعْمَلُوْنَ', 'Dan Allah Maha Mengetahui apa yang mereka kerjakan', 'Tak ada yang luput dari penglihatan Ku. Setiap air matamu, setiap sabarmu, semua Aku catat', 'Bersyukurlah dan lakukanlah satu hal kecil yang selama ini belum kamukerjakan dalam diam', NOW(), NOW()),
(31, 1, 'QS At Talaq : 3', 'وَمَنْ يَّتَوَكَّلْ عَلَى اللّٰهِ فَهُوَ حَسْبُهٗ ۗ اِنَّ اللّٰهَ بَالِغُ اَمْرِهٖ', 'Dan barangsiapa bertawakal kepada Allah, niscaya Allah akan mencukupkan (keperluan)nya.', 'Aku tidak membiarkanmu berjuang sendiri. Tawakalmu adalah pintu datangnya pertolonganKu', 'Hari ini pasrahkan semua urusanmu seteah berusaha meksimal.Jangan panik', NOW(), NOW()),
(32, 1, 'QS Al Mumtahanah : 4', 'رَبَّنَا عَلَيْكَ تَوَكَّلْنَا وَاِلَيْكَ اَنَبْنَا', 'Kami bertawakal kepada Allah. KepadaNya kami berserah', 'Kamu bisa tenang jika tahu Aku yang mengurus hasilnya', 'Bayangkan keinginanmu hari ini sudah Allah berikan, sambil lisan mengucap \"Yaa Hasiib ... Yaa Rozaaq\"', NOW(), NOW()),
(33, 1, 'QS Ghafir : 60', 'اَسْتَجِبْ لَكُمْۗ اِنَّ الَّذِيْنَ يَسْتَكْبِرُوْنَ', 'Berdo\'alah kepadaKu, niscaya akan Kuperkenankan bagimu', 'Jangan tunda do\'a hari ini,sebab Aku lebih dekat dari detak hatimu', 'Sisihkan waktu 5 menit untuk do\'a penuh keyakinan dan harap', NOW(), NOW()),
(34, 1, 'QS Al Anfal : 9', 'اِذْ تَسْتَغِيْثُوْنَ رَبَّكُمْ فَاسْتَجَابَ لَكُمْ', '(Ingatlah) ketika kamu memohon pertolongan kepada Tuhanmu, lalu Dia mengabulkan(-nya)', 'Tangismu tak pernah sia-sia. Aku mendengar setiap desahmu. PertolonganKu lebih dekat dari yang kaubayangkan', 'Ucapkan satu do\'a sambil sujud hari ini', NOW(), NOW()),
(35, 1, 'QS At Talaq: 2-3', 'وَمَنۡ يَّتَّقِ اللّٰهَ يَجۡعَلۡ لَّهٗ مَخۡرَجًا ۙ', 'Barangsiapa bertakwa kepada Allah niscaya Dia akan membukakan jalan keluar baginya', 'Ketaatanmu takkan sia-sia.Bersabarlah, Aku sedang menyiapkan keajaiban dariarah yang tak kau sangka', 'Hindari satu maksiat hari ini dan tambah amalanmu sebagai bentuk takwamu', NOW(), NOW()),
(36, 1, 'QS Ghafir : 60', 'رَبُّكُمُ ادْعُوْنِيْٓ اَسْتَجِبْ لَكُمْۗ', '“Berdoalah kepada-Ku, niscaya akan Aku perkenankan bagimu\"', 'Tak perlu kata indah, Aku tahu isi hatimu.Cukup datang padaKu dan Aku akan bukakan jalan', 'Tulis satu do\'a yang paling kamu harapkan dan bacakan sebelum tidur', NOW(), NOW()),
(37, 1, 'QS An Nahl : 97', 'مَنْ عَمِلَ صَالِحًا مِّنْ ذَكَرٍ اَوْ اُنْثٰى وَهُوَ مُؤْمِنٌ فَلَنُحْيِيَنَّهٗ حَيٰوةً طَيِّبَةًۚ', '\"Barangsiapa mengerjakan kebajikan, baik laki-laki maupun perempuan dalam keadaan beriman, maka pasti akan Kami berikan kepadanya kehidupan yang baik\"', 'Kebaikanmu takkan hilang. Aku balaas dengan hidup yang damai', 'Ambil satu niat kecil hari ini, berbuat baik dengan senyum atau sedekah', NOW(), NOW()),
(38, 1, 'QS. Al-hajj:78', 'جِهَادِهِۦۚ هُوَ ٱجْتَبَىٰكُمْ وَمَا جَعَلَ عَلَيْكُمْ فِى ٱلدِّينِ مِنْ حَرَجٍۚ', '\"Dia telah memilih kamu, dan Dia tidak menjadikan kesukaran untukmu dalam agama.\"', '\"Aku tidak menciptakan jalan-Ku untuk menyulitkanmu-tapi untuk membebaskanmu\"', 'Dekatkan dirimu pada ibadah yang ringan, tapi konsisten hari ini', NOW(), NOW());

SET FOREIGN_KEY_CHECKS = 1;
